# Site settings
baseurl: "/doxuaphuocsang"
name: "Đồ Xưa Phước Sang"
theme: "classic"

# Build settings
markdown: kramdown
permalink: /:categories/:title-0903855187.html
excerpt_separator: "\n\n"
paginate: 12